// <auto-generated />
using System;
using KonsiLoja.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KonsiLoja.Migrations
{
    [DbContext(typeof(KonsiContexto))]
    [Migration("20210906223305_Primeira")]
    partial class Primeira
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KonsiLoja.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CPF")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VendedoresId")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.HasIndex("VendedoresId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("KonsiLoja.Models.Contrato", b =>
                {
                    b.Property<int>("ContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientesId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroContrato")
                        .HasColumnType("int");

                    b.Property<int>("ParcelasPagas")
                        .HasColumnType("int");

                    b.Property<int>("ParcelasTotais")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoDevedor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorContrato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValorParcela")
                        .HasColumnType("int");

                    b.Property<int?>("VendedoresId")
                        .HasColumnType("int");

                    b.HasKey("ContratoId");

                    b.HasIndex("ClientesId")
                        .IsUnique()
                        .HasFilter("[ClientesId] IS NOT NULL");

                    b.HasIndex("VendedoresId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("KonsiLoja.Models.Vendedor", b =>
                {
                    b.Property<int>("VendedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VendedorId");

                    b.ToTable("Vendedors");
                });

            modelBuilder.Entity("KonsiLoja.Models.Cliente", b =>
                {
                    b.HasOne("KonsiLoja.Models.Vendedor", "Vendedores")
                        .WithMany("Clientes")
                        .HasForeignKey("VendedoresId");
                });

            modelBuilder.Entity("KonsiLoja.Models.Contrato", b =>
                {
                    b.HasOne("KonsiLoja.Models.Cliente", "Clientes")
                        .WithOne("Contrato")
                        .HasForeignKey("KonsiLoja.Models.Contrato", "ClientesId");

                    b.HasOne("KonsiLoja.Models.Vendedor", "Vendedores")
                        .WithMany("Contratos")
                        .HasForeignKey("VendedoresId");
                });
#pragma warning restore 612, 618
        }
    }
}
